/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  Sizes,
  Type,
  Variance,
} from './components/common/styles';
import {
  Align,
  Direction,
  Justify,
} from './components/common/flex';

export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface DemoButton {}
  interface DemoNav {}
  interface PageNotFound {}
  interface ShftButton {
    'class': string;
    'disabled': boolean;
    'size': Sizes;
    'type': Type;
    'variance': Variance;
  }
  interface ShftCard {
    'class': string;
  }
  interface ShftCheckbox {
    'checked': boolean;
    'class': string;
    'disabled': boolean;
  }
  interface ShftContainer {
    'class': string;
  }
  interface ShftDropdown {
    'alignSelf': Align;
    'class': string;
    'disabled': boolean;
    'flexGrow': number;
    'flexShrink': number;
    'justifySelf': Justify;
  }
  interface ShftFlex {
    'alignContent': Align;
    'alignItems': Align;
    'alignSelf': Align;
    'class': string;
    'flexDirection': Direction;
    'inline': boolean;
    'justifyContent': Justify;
    'justifyItems': Justify;
    'justifySelf': Justify;
  }
  interface ShftRadio {
    'alignSelf': Align;
    'checked': boolean;
    'class': string;
    'disabled': boolean;
    'flexGrow': number;
    'flexShrink': number;
    'group': string;
    'justifySelf': Justify;
  }
  interface ShftSlider {
    'class': string;
    'disabled': boolean;
    'tickIntervals': number;
  }
  interface ShftTab {
    'class': string;
    'disabled': boolean;
    'key': string;
  }
  interface ShftTabs {
    'class': string;
    'disabled': boolean;
    'setActiveTab': (key: string) => Promise<void>;
  }
  interface ShftTextbox {
    'class': string;
    'disabled': boolean;
    'multiline': boolean;
    'value': string;
  }
  interface ShftWindow {
    'class': string;
    'close': boolean;
    'disabled': boolean;
    'maximize': boolean;
    'minimize': boolean;
    'title': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDemoButtonElement extends Components.DemoButton, HTMLStencilElement {}
  var HTMLDemoButtonElement: {
    prototype: HTMLDemoButtonElement;
    new (): HTMLDemoButtonElement;
  };

  interface HTMLDemoNavElement extends Components.DemoNav, HTMLStencilElement {}
  var HTMLDemoNavElement: {
    prototype: HTMLDemoNavElement;
    new (): HTMLDemoNavElement;
  };

  interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {}
  var HTMLPageNotFoundElement: {
    prototype: HTMLPageNotFoundElement;
    new (): HTMLPageNotFoundElement;
  };

  interface HTMLShftButtonElement extends Components.ShftButton, HTMLStencilElement {}
  var HTMLShftButtonElement: {
    prototype: HTMLShftButtonElement;
    new (): HTMLShftButtonElement;
  };

  interface HTMLShftCardElement extends Components.ShftCard, HTMLStencilElement {}
  var HTMLShftCardElement: {
    prototype: HTMLShftCardElement;
    new (): HTMLShftCardElement;
  };

  interface HTMLShftCheckboxElement extends Components.ShftCheckbox, HTMLStencilElement {}
  var HTMLShftCheckboxElement: {
    prototype: HTMLShftCheckboxElement;
    new (): HTMLShftCheckboxElement;
  };

  interface HTMLShftContainerElement extends Components.ShftContainer, HTMLStencilElement {}
  var HTMLShftContainerElement: {
    prototype: HTMLShftContainerElement;
    new (): HTMLShftContainerElement;
  };

  interface HTMLShftDropdownElement extends Components.ShftDropdown, HTMLStencilElement {}
  var HTMLShftDropdownElement: {
    prototype: HTMLShftDropdownElement;
    new (): HTMLShftDropdownElement;
  };

  interface HTMLShftFlexElement extends Components.ShftFlex, HTMLStencilElement {}
  var HTMLShftFlexElement: {
    prototype: HTMLShftFlexElement;
    new (): HTMLShftFlexElement;
  };

  interface HTMLShftRadioElement extends Components.ShftRadio, HTMLStencilElement {}
  var HTMLShftRadioElement: {
    prototype: HTMLShftRadioElement;
    new (): HTMLShftRadioElement;
  };

  interface HTMLShftSliderElement extends Components.ShftSlider, HTMLStencilElement {}
  var HTMLShftSliderElement: {
    prototype: HTMLShftSliderElement;
    new (): HTMLShftSliderElement;
  };

  interface HTMLShftTabElement extends Components.ShftTab, HTMLStencilElement {}
  var HTMLShftTabElement: {
    prototype: HTMLShftTabElement;
    new (): HTMLShftTabElement;
  };

  interface HTMLShftTabsElement extends Components.ShftTabs, HTMLStencilElement {}
  var HTMLShftTabsElement: {
    prototype: HTMLShftTabsElement;
    new (): HTMLShftTabsElement;
  };

  interface HTMLShftTextboxElement extends Components.ShftTextbox, HTMLStencilElement {}
  var HTMLShftTextboxElement: {
    prototype: HTMLShftTextboxElement;
    new (): HTMLShftTextboxElement;
  };

  interface HTMLShftWindowElement extends Components.ShftWindow, HTMLStencilElement {}
  var HTMLShftWindowElement: {
    prototype: HTMLShftWindowElement;
    new (): HTMLShftWindowElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'demo-button': HTMLDemoButtonElement;
    'demo-nav': HTMLDemoNavElement;
    'page-not-found': HTMLPageNotFoundElement;
    'shft-button': HTMLShftButtonElement;
    'shft-card': HTMLShftCardElement;
    'shft-checkbox': HTMLShftCheckboxElement;
    'shft-container': HTMLShftContainerElement;
    'shft-dropdown': HTMLShftDropdownElement;
    'shft-flex': HTMLShftFlexElement;
    'shft-radio': HTMLShftRadioElement;
    'shft-slider': HTMLShftSliderElement;
    'shft-tab': HTMLShftTabElement;
    'shft-tabs': HTMLShftTabsElement;
    'shft-textbox': HTMLShftTextboxElement;
    'shft-window': HTMLShftWindowElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface DemoButton extends JSXBase.HTMLAttributes<HTMLDemoButtonElement> {}
  interface DemoNav extends JSXBase.HTMLAttributes<HTMLDemoNavElement> {}
  interface PageNotFound extends JSXBase.HTMLAttributes<HTMLPageNotFoundElement> {}
  interface ShftButton extends JSXBase.HTMLAttributes<HTMLShftButtonElement> {
    'class'?: string;
    'disabled'?: boolean;
    'size'?: Sizes;
    'type'?: Type;
    'variance'?: Variance;
  }
  interface ShftCard extends JSXBase.HTMLAttributes<HTMLShftCardElement> {
    'class'?: string;
  }
  interface ShftCheckbox extends JSXBase.HTMLAttributes<HTMLShftCheckboxElement> {
    'checked'?: boolean;
    'class'?: string;
    'disabled'?: boolean;
  }
  interface ShftContainer extends JSXBase.HTMLAttributes<HTMLShftContainerElement> {
    'class'?: string;
  }
  interface ShftDropdown extends JSXBase.HTMLAttributes<HTMLShftDropdownElement> {
    'alignSelf'?: Align;
    'class'?: string;
    'disabled'?: boolean;
    'flexGrow'?: number;
    'flexShrink'?: number;
    'justifySelf'?: Justify;
  }
  interface ShftFlex extends JSXBase.HTMLAttributes<HTMLShftFlexElement> {
    'alignContent'?: Align;
    'alignItems'?: Align;
    'alignSelf'?: Align;
    'class'?: string;
    'flexDirection'?: Direction;
    'inline'?: boolean;
    'justifyContent'?: Justify;
    'justifyItems'?: Justify;
    'justifySelf'?: Justify;
  }
  interface ShftRadio extends JSXBase.HTMLAttributes<HTMLShftRadioElement> {
    'alignSelf'?: Align;
    'checked'?: boolean;
    'class'?: string;
    'disabled'?: boolean;
    'flexGrow'?: number;
    'flexShrink'?: number;
    'group'?: string;
    'justifySelf'?: Justify;
  }
  interface ShftSlider extends JSXBase.HTMLAttributes<HTMLShftSliderElement> {
    'class'?: string;
    'disabled'?: boolean;
    'tickIntervals'?: number;
  }
  interface ShftTab extends JSXBase.HTMLAttributes<HTMLShftTabElement> {
    'class'?: string;
    'disabled'?: boolean;
    'key'?: string;
  }
  interface ShftTabs extends JSXBase.HTMLAttributes<HTMLShftTabsElement> {
    'class'?: string;
    'disabled'?: boolean;
  }
  interface ShftTextbox extends JSXBase.HTMLAttributes<HTMLShftTextboxElement> {
    'class'?: string;
    'disabled'?: boolean;
    'multiline'?: boolean;
    'value'?: string;
  }
  interface ShftWindow extends JSXBase.HTMLAttributes<HTMLShftWindowElement> {
    'class'?: string;
    'close'?: boolean;
    'disabled'?: boolean;
    'maximize'?: boolean;
    'minimize'?: boolean;
    'title'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'demo-button': DemoButton;
    'demo-nav': DemoNav;
    'page-not-found': PageNotFound;
    'shft-button': ShftButton;
    'shft-card': ShftCard;
    'shft-checkbox': ShftCheckbox;
    'shft-container': ShftContainer;
    'shft-dropdown': ShftDropdown;
    'shft-flex': ShftFlex;
    'shft-radio': ShftRadio;
    'shft-slider': ShftSlider;
    'shft-tab': ShftTab;
    'shft-tabs': ShftTabs;
    'shft-textbox': ShftTextbox;
    'shft-window': ShftWindow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


